---
title: "Exploring Gapminder"
output: github_document
---

Loading the libraries

```{r,message=FALSE}
library(gapminder)
library(tidyverse)
```

Q1) What type is gapminder?
```{r}
typeof(gapminder)
```

Q2) What is the class on gapminder

```{r}
class(gapminder)
```


Q3) How many variables/columns?

```{r}
print("Coloumn equal to:")
ncol(gapminder)
```

Q4) How many rows/observations?

```{r}
print("Rows equal to:")
nrow(gapminder)
```

Q5) Can you get these facts about “extent” or “size” in more than one way? Can you imagine different functions being useful in different contexts?
 
```{r}
#way 1 using dim command
print("way 1 using dim command")
print("Rows equal to:")
dim(gapminder)[1] 
print("Coloumn equal to:")
dim(gapminder)[2]
#way two using length and transpose command
print("way two using length and transpose command")
print("Rows equal to:")
length(transpose(gapminder))
print("Coloumn equal to:")
length(gapminder)
```

Q6) What data type is each variable?

```{r}
sapply(gapminder,typeof)
```



